server:
  port: ${PORT:8874}
  message: Configuración local en el servidor levantado

spring:
  application:
    name: platos-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backend?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
    eureka-server-read-timeout-seconds: 60
    eureka-server-connect-timeout-seconds: 60
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
